"""update file_uploads schema

Revision ID: 97dc7c031a42
Revises: 6c160312be41
Create Date: 2026-01-02 03:26:23.014058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97dc7c031a42'
down_revision: Union[str, Sequence[str], None] = '6c160312be41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('exp_name', sa.String(), nullable=True))
    op.add_column('file_uploads', sa.Column('experiment_id', sa.String(), nullable=True))
    op.add_column('file_uploads', sa.Column('exposures_filename', sa.String(), nullable=True))
    op.add_column('file_uploads', sa.Column('events_filename', sa.String(), nullable=True))
    op.add_column('file_uploads', sa.Column('users_filename', sa.String(), nullable=True))
    op.drop_column('file_uploads', 'csv_filenames')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_uploads', sa.Column('csv_filenames', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('file_uploads', 'users_filename')
    op.drop_column('file_uploads', 'events_filename')
    op.drop_column('file_uploads', 'exposures_filename')
    op.drop_column('file_uploads', 'experiment_id')
    op.drop_column('file_uploads', 'exp_name')
    # ### end Alembic commands ###
